# Generated by Django 3.2.9 on 2022-04-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeExternes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longueur', models.FloatField(max_length=999999)),
                ('largeur', models.FloatField(max_length=999999)),
                ('hauteur', models.FloatField(max_length=999999)),
                ('degre', models.FloatField(max_length=999999)),
                ('typeIsolant', models.FloatField(max_length=999999)),
                ('typeEntrepot', models.CharField(max_length=999999)),
                ('region', models.CharField(max_length=999999)),
                ('chargeExterneMurNordEtSud', models.FloatField(max_length=999999)),
                ('chargeExterneMurOuestEtEst', models.FloatField(max_length=999999)),
                ('chargeExternePlafond', models.FloatField(max_length=999999)),
                ('chargeExternePlancher', models.FloatField(max_length=999999)),
                ('surfaceNordEtSud', models.FloatField(max_length=999999)),
                ('surfaceOuestEtEst', models.FloatField(max_length=999999)),
                ('surfacePlancherEtPlafond', models.FloatField(max_length=999999)),
                ('temperatureInterieure', models.FloatField(max_length=999999)),
                ('KmurEtPlafond', models.FloatField(max_length=999999)),
                ('Kplancher', models.FloatField(max_length=999999)),
                ('temperatureExterieure', models.FloatField(max_length=999999)),
                ('coeffConductivite', models.FloatField(max_length=999999)),
                ('epaisseurIsolant', models.FloatField(max_length=999999)),
                ('apportParTransmissionATraversLesParois', models.FloatField(max_length=999999)),
                ('volume', models.FloatField(max_length=999999)),
                ('apportParRenouvellementDAir', models.FloatField(max_length=999999)),
                ('nombreRenouvellementDAir', models.FloatField(max_length=999999)),
                ('totalChargeExternes', models.FloatField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeInternes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dureeMoyenneDOccupationParLePersonnel', models.FloatField(max_length=999999)),
                ('nombrePersonnesPresentesCF', models.FloatField(max_length=999999)),
                ('qteChaleurDegageeParUnePersonne', models.FloatField(max_length=999999)),
                ('masseDenree', models.FloatField(max_length=999999)),
                ('temperatureIntroductionDenree', models.FloatField(max_length=999999)),
                ('apportRespirationDenrees', models.FloatField(max_length=999999)),
                ('chargesDuEclairage', models.FloatField(max_length=999999)),
                ('chargesDuPersonnes', models.FloatField(max_length=999999)),
                ('apportDuDenreesEntrantes', models.FloatField(max_length=999999)),
                ('totalChargeInternes', models.FloatField(max_length=999999)),
                ('chargeExternes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.chargeexternes')),
            ],
        ),
        migrations.CreateModel(
            name='PuissanceFrigorifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeFrigorifiqueIntermediaire', models.FloatField(max_length=999999)),
                ('dureeJournaliereFonctionnementInstallation', models.FloatField(max_length=999999)),
                ('puissanceFrigorifiqueIntermediaireEvaporateur', models.FloatField(max_length=999999)),
                ('puissanceEffectiveEvaporateur', models.FloatField(max_length=999999)),
                ('chargeInternes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.chargeinternes')),
            ],
        ),
    ]
